# Generated by Django 6.0.6 on 2026-06-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_can_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_funds_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
