# Generated by Django 6.0.6 on 2026-06-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_seed_promice_data'),
        ('doctors', '0013_doctor_photo'),
        ('patients', '0003_patient_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAssessmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_take_assessment', models.BooleanField(default=True)),
                ('last_activated_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_profile', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_assessments', to='doctors.doctor')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='assessments.assessmentresult')),
            ],
            options={
                'unique_together': {('doctor', 'assessment')},
            },
        ),
    ]
