# Generated by Django 6.0.6 on 2026-06-11 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('BUG', 'Technical Bug / Error'), ('SUGGESTION', 'Suggestion / Improvement'), ('OTHER', 'Other Issues')], default='BUG', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(choices=[('NONE', 'No Action Taken'), ('FUNDS_FROZEN', 'Financial Funds Frozen'), ('ACCOUNT_SUSPENDED', 'Account Temporarily Suspended'), ('ACCOUNT_DELETED', 'Account Permanently Deleted'), ('DISMISSED', 'Report Dismissed / Ignored')], default='NONE', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes written by the administrator regarding this action.', null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_user_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_user_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
