# Generated by Django 6.0.6 on 2026-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_appreport_userreport_delete_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appreport',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userreport',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='appreport',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='appreport',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='reported_user',
        ),
        migrations.AddField(
            model_name='appreport',
            name='reason',
            field=models.CharField(choices=[('appBug', 'App Bug / Issue'), ('crashOrFreeze', 'App Crashes or Freezes'), ('paymentIssue', 'Payment or Transaction Issue'), ('other', 'Other Issue')], default='other', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reason',
            field=models.CharField(choices=[('unprofessional', 'Unprofessional Behavior'), ('harassment', 'Harassment'), ('inappropriateContent', 'Inappropriate Content'), ('missingAppointment', 'Missing Appointment'), ('other', 'Other Issue')], default='other', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreport',
            name='report_type',
            field=models.CharField(choices=[('doctor', 'Doctor Report'), ('session', 'Session Report')], default='doctor', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='userreport',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='target_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appreport',
            name='report_type',
            field=models.CharField(default='app', max_length=15),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
