# Generated by Django 6.0.6 on 2026-06-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0015_appointment_created_at'),
        ('doctors', '0013_doctor_photo'),
        ('patients', '0003_patient_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('prescription_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', '-created_at'], name='rx_doctor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-created_at'], name='rx_patient_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(condition=models.Q(('diagnosis', ''), _negated=True), name='rx_diagnosis_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionmedication',
            constraint=models.CheckConstraint(condition=models.Q(('medication_name', ''), _negated=True), name='rx_med_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionmedication',
            constraint=models.CheckConstraint(condition=models.Q(('dosage', ''), _negated=True), name='rx_med_dosage_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionmedication',
            constraint=models.CheckConstraint(condition=models.Q(('frequency', ''), _negated=True), name='rx_med_freq_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionmedication',
            constraint=models.CheckConstraint(condition=models.Q(('duration', ''), _negated=True), name='rx_med_duration_not_blank'),
        ),
    ]
