# Generated by Django 6.0.6 on 2026-06-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='نسبة الإدارة من الجلسة', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='doctor_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='المبلغ المستحق للطبيب', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_transferred_to_doctor',
            field=models.BooleanField(default=False, help_text='هل تم تحويل مستحقات الطبيب إليه؟'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='المبلغ الكلي المدفوع من المريض', max_digits=10),
        ),
    ]
