# Generated by Django 6.0.6 on 2026-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_payment_admin_commission_payment_doctor_amount_and_more'),
        ('doctors', '0013_doctor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveConstraint(
            model_name='sessionprice',
            name='unique_doctor_session_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='viewed_by',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred to Doctor'), ('refunded', 'Refunded'), ('partial', 'Partial Payment')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('missed', 'Missed'), ('patient_missed', 'Patient Missed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice'), ('video', 'Video')], default='chat', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='doctor_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_transferred_to_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionprice',
            name='type',
            field=models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice'), ('video', 'Video')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='sessionprice',
            unique_together={('doctor', 'type')},
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
