# Generated by Django 6.0.6 on 2026-06-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_remove_medication_prescription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
