# Generated by Django 6.0.6 on 2026-06-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_alter_payment_admin_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='has_next_session',
            field=models.BooleanField(default=False),
        ),
    ]
