"""
Django settings for project4th project.

Generated by 'django-admin startproject' using Django 5.1.1.
"""

from datetime import timedelta
from decimal import Decimal
import os
from pathlib import Path
from decouple import RepositoryEnv, config
from uvicorn import Config

# 1. تحديد مسار المشروع الرئيسي (حيث يوجد manage.py)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 2. إجبار decouple على قراءة الملف من المسار الصحيح
env_file_path = os.path.join(BASE_DIR, '.env')
config = Config(RepositoryEnv(env_file_path))

# 3. الآن استخدم config كما كنت تستخدمه
SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)

# النطاقات المسموحة للعمل على السيرفر المحلي والإنتاج
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default="alihammadi.pythonanywhere.com,127.0.0.1,localhost").split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # تطبيقات المشروع الأساسية
    'users',
    'patients',
    'doctors.apps.DoctorsConfig',
    'appointments',
    'assessments',
    'notifications',
    'reports',
    'ratings',
    'articles',
    'musics',
    'notes',
    # المكتبات الخارجية والإضافات
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'appointments.middleware.CancelExpiredAppointmentsMiddleware', 
]

ROOT_URLCONF = 'project4th.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project4th.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static & Media Files Configurations
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'
 
# Google Authentication Config
GOOGLE_CLIENT_ID = "1003547921607-12juc731vap30cbmmfjtkf38tr09ck8b.apps.googleusercontent.com"


# Django Rest Framework Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

# Documentation (Swagger / Spectacular) Config
SPECTACULAR_SETTINGS = {
    'TITLE': 'Afiete Project API',
    'DESCRIPTION': 'Backend endpoints documentation for Afiete Application',
    'VERSION': '1.0.0',
    'DISABLE_ERRORS': True,
    'SERVERS': [
        {'url': 'https://alihammadi.pythonanywhere.com', 'description': 'Production Server'},
        {'url': 'http://127.0.0.1:8000', 'description': 'Local Development Server'},
    ],
}

# JWT Token Configurations
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

# Email Configurations (SMTP) - Secured via .env
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='your@gmail.com')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='your@gmail.com')

# Celery Broker & Beat Configurations
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'delete-unverified-users': {
        'task': 'users.tasks.delete_unverified_users',
        'schedule': crontab(hour=3, minute=0),  # تنفيذ المهمة يومياً الساعة 3 صباحاً
    },
}

# نسبة عمولة المنصة الثابتة (20%) يتم استدعاؤها داخل الموديل عند اللزوم
COMMISSION_RATE = Decimal('0.20')